### ISSUE TITLE
Docs return in JSON as well

### ISSUE THREAD

**Issue by kpaxton** [clearlydecoded/rest-messenger#34]
It would be nice to have the docs endpoint return JSON so that as an external service, I could auto discover what endpoints are available. This would allow the listing of available messages in a selection list for users for actions that can be taken.

**Comment by ychaikin** [comment]
Hmm... I am not sure the spirit of this story is satisfied by simply exposing the documentation object in JSON.

While that's done, the issue is that the actual model representation is just a string, not some JSON model. 

So, this ticket has to be reopened and solved by exposing the actual JSON schema directly to the client. Currently, I am hiding the JSON schema as I didn't think anyone would care for it, but clearly that's not the case.

**Comment by ychaikin** [comment]
closed wrong issue.

**Comment by ychaikin** [comment]
Solution which is merged into development directly addresses the ticket as described. Will do the more broad purpose of this ticket in another ticket. See #39.
