### ISSUE TITLE
Response should be sent with application/json;charset=UTF-8, not just application/json

### ISSUE THREAD

**Issue by Steve973** [clearlydecoded/rest-messenger#50]
It looks like the content headers are set to application/json, but it would be nice to have a setting that allows the user to specifically set the content type.  e.g., `application/json;charset=UTF-8`

**Comment by ychaikin** [comment]
Correct, this is done in [SpringRestMessenger.java](https://github.com/clearlydecoded/rest-messenger/blob/master/src/main/java/com/clearlydecoded/messenger/rest/SpringRestMessenger.java):
```java
RequestMappingInfo messageProcessingRequestMappingInfo = RequestMappingInfo
        .paths(endpointUri)
        .methods(RequestMethod.POST)
        .consumes(MediaType.APPLICATION_JSON_VALUE)
        .produces(MediaType.APPLICATION_JSON_VALUE)
        .build();
```

I guess, I am more inclined to classify this as a bug/improvement and change it to `application/json;charset=UTF-8` instead of letting the user define these things. The idea behind this framework is to make things straightforward for a particular use case - request/response scenario. If the user requires something more custom, regular Spring REST is available to customize things as much as they want. However, this framework's value is in its laser focus on one specific, yet super common, use case.

Is there another use case that I am not thinking of where a non-JSON or a non-UTF-8 charset would fit?? Let me know. Otherwise, I can just implement this as an improvement. Very simple change.

**Comment by Steve973** [comment]
The issue was that it was using application/json but the charset was one of the ISO charsets.  I had to use an interceptor that changes the charset to UTF-8.  For my use case, json is perfectly fine, but I could see some people possibly wanting to use XML.  Either way, I think that a charset of UTF-8 would suffice in both cases.   Is there any reason why a user should not be able to specify the media type value for themselves (if they do not want to accept the default)?

I am not sure what I did today that broke the interaction between two services that I was working with and caused the encoding to get wonky.

**Comment by ychaikin** [comment]
The reason for not providing this choice to the user is because it starts to blur the lines between a straightforward simple framework for this particular use case and full blown Spring REST. If the user wants to do XML, this isn't the framework for them. This framework's goal was the simplest possible request object in, response object out type of case.
